---
- hosts: predict
  become: yes
  become_user: root
  tasks:
  - name: clone repo
    git: >
      repo=https://github.com/yatinsharma7/Customer_Churn.git
      update=yes
      dest=/opt/predict
      version=master
      accept_hostkey=yes
      force=yes
    tags:
      - clone-repo
  - name: Install list of required apt packages
    apt: name={{item}} state=installed
    with_items:
    - python-dev
    - python-pip
    - libfreetype6-dev
    - libatlas-base-dev
    become: yes
    become_user: root
  - name: install python packages 
    command: pip install -r /opt/predict/code/requirements.txt
    tags:
      - install-python-packages
  - name: Fix 'predict' folder permissions
    file: path=/opt/predict owner=hadoop group=hadoop mode=0775 state=directory recurse=yes
    tags:
      - set-Hadoop permissions

